# Generated by Django 4.2 on 2023-04-20 18:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("restaurant", "0003_alter_menu_users_voted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="users_voted",
            field=models.ManyToManyField(
                blank=True, null=True, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
